# In vitro assay analysis


## Directory structure

Data is organized in the following structure:

```
data/
├── metadata.csv
├── images/
│   ├── 1_bf.tif
│   ├── 1_g.tif
│   ├── 1_r.tif
│   ├── 2_0.tif
│   └── ...

## metadata.csv example
figure_name,figure_id,channel,seeding_density,virus,cargo,dose_vg/well,image_time_h,receptor,include,notes
1_bf.tif,1,brightfield,0.5e5,AAV9,EGFP,0.5e10,24,EGFRvIII,1,
1_r.tif,1,brightfield,0.5e5,AAV9,EGFP,0.5e10,24,EGFRvIII,1,
```

In [3]:
import pandas as pd
from cellseg.metadata import metadata

data = '/Users/longwei/Desktop/janglab/figures/2026-05-22-in_vitro_assay_transduction_24h/'
meta = data + 'metadata.csv'
result = data + 'in_vitro_assay_results.csv'
# Load or generate metadata
df_metadata = metadata(data_dir=data, verbose=True)
print("\nMetadata:")
df_metadata

Looking for metadata file at: /Users/longwei/Desktop/janglab/figures/2026-05-22-in_vitro_assay_transduction_24h/metadata.csv
Looking for images in: /Users/longwei/Desktop/janglab/figures/2026-05-22-in_vitro_assay_transduction_24h/images
✓ Found and loaded metadata file (144 rows)

Metadata:

,figure_name,figure_id,experiment_id,magnification,channel,seeding_density,virus,cargo,dose_vg/well,image_time_h,receptor,include,notes
0,Image001.tif,1,1,4x,bf,50000,AAV6,EGFP,5.000000e+10,24,EGFRvIII,1,NaN
1,Image002.tif,2,1,4x,r,50000,AAV6,EGFP,5.000000e+10,24,EGFRvIII,1,NaN
2,Image003.tif,3,1,4x,g,50000,AAV6,EGFP,5.000000e+10,24,EGFRvIII,1,NaN
3,Image004.tif,4,2,4x,bf,50000,AAV6,EGFP,5.000000e+10,24,EGFRvIII,1,NaN
4,Image005.tif,5,2,4x,r,50000,AAV6,EGFP,5.000000e+10,24,EGFRvIII,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,Image140.tif,140,47,4x,r,50000,AAV9,EGFP,2.500000e+09,24,Control,1,NaN
140,Image141.tif,141,47,4x,g,50000,AAV9,EGFP,2.500000e+09,24,Control,1,NaN
141,Image142.tif,142,48,4x,bf,50000,AAV9,EGFP,2.500000e+09,24,Control,1,NaN
142,Image143.tif,143,48,4x,r,50000,AAV9,EGFP,2.500000e+09,24,Control,1,NaN
143,Image144.tif,144,48,4x,g,50000,AAV9,EGFP,2.500000e+09,24,Control,1,NaN

In [6]:
from cellseg.quant import assay_rg_overlap_analysis

df_results = assay_rg_overlap_analysis(
    df_metadata,
    image_directory=data + 'images/',
    output_file='rg_overlap_results.csv',
    bf_label='bf',
    r_label='r',
    g_label='g',
    r_channel=0,
    g_channel=1,
    min_r_intensity=0.05,
)

Processing RG overlap: 100%|██████████| 48/48 [01:36<00:00,  2.01s/it]

In [7]:
df_results

,experiment_id,status,error,magnification,seeding_density,virus,cargo,dose_vg/well,image_time_h,receptor,...,bf_area,r_area,r_intensity,r_filter,g_area,overlapping_area,overlap_r,overlap_g,g_intensity_all,g_intensity_overlap
0,1,ok,,4x,50000,AAV6,EGFP,5.000000e+10,24,EGFRvIII,...,136459,16787,0.151356,False,33144,4544,0.270686,0.137099,0.568936,0.590942
1,2,ok,,4x,50000,AAV6,EGFP,5.000000e+10,24,EGFRvIII,...,125664,13186,0.152658,False,31249,4242,0.321705,0.135748,0.592918,0.593209
2,3,ok,,4x,50000,AAV6,EGFP,5.000000e+10,24,EGFRvIII,...,127888,14772,0.164497,False,25374,3155,0.213580,0.124340,0.561718,0.580006
3,4,ok,,4x,50000,AAV6,EGFP,2.500000e+10,24,EGFRvIII,...,115449,13761,0.167211,False,21809,3632,0.263934,0.166537,0.398763,0.404263
4,5,ok,,4x,50000,AAV6,EGFP,2.500000e+10,24,EGFRvIII,...,108394,10982,0.124767,False,16033,3472,0.316154,0.216553,0.409681,0.411714
5,6,ok,,4x,50000,AAV6,EGFP,2.500000e+10,24,EGFRvIII,...,113505,11571,0.150269,False,18594,2735,0.236367,0.147090,0.400027,0.422250
6,7,ok,,4x,50000,AAV6,EGFP,5.000000e+09,24,EGFRvIII,...,143013,16510,0.179192,False,18690,3285,0.198970,0.175762,0.231612,0.249400
7,8,ok,,4x,50000,AAV6,EGFP,5.000000e+09,24,EGFRvIII,...,111923,12129,0.149172,False,13128,1935,0.159535,0.147395,0.247120,0.297316
8,9,ok,,4x,50000,AAV6,EGFP,5.000000e+09,24,EGFRvIII,...,109287,14027,0.160436,False,12586,2984,0.212733,0.237089,0.246273,0.259902
9,10,ok,,4x,50000,AAV6,EGFP,2.500000e+09,24,EGFRvIII,...,137514,15740,0.173023,False,11129,2187,0.138945,0.196514,0.196049,0.223858
10,11,ok,,4x,50000,AAV6,EGFP,2.500000e+09,24,EGFRvIII,...,129812,16789,0.168742,False,14553,2486,0.148073,0.170824,0.195691,0.222862
11,12,ok,,4x,50000,AAV6,EGFP,2.500000e+09,24,EGFRvIII,...,121911,13991,0.145637,False,18455,3537,0.252805,0.191655,0.185320,0.213406
12,13,ok,,4x,50000,AAV6,EGFP,5.000000e+10,24,Control,...,105857,0,0.011767,True,25037,0,NaN,0.000000,0.551511,NaN
13,14,ok,,4x,50000,AAV6,EGFP,5.000000e+10,24,Control,...,103031,0,0.011776,True,25025,0,NaN,0.000000,0.564849,NaN
14,15,ok,,4x,50000,AAV6,EGFP,5.000000e+10,24,Control,...,133190,0,0.025252,True,33827,0,NaN,0.000000,0.554888,NaN
15,16,ok,,4x,50000,AAV6,EGFP,2.500000e+10,24,Control,...,71842,0,0.011765,True,15438,0,NaN,0.000000,0.336876,NaN
16,17,ok,,4x,50000,AAV6,EGFP,2.500000e+10,24,Control,...,119220,0,0.011765,True,17831,0,NaN,0.000000,0.416610,NaN
17,18,ok,,4x,50000,AAV6,EGFP,2.500000e+10,24,Control,...,108169,0,0.013074,True,17597,0,NaN,0.000000,0.394434,NaN
18,19,ok,,4x,50000,AAV6,EGFP,5.000000e+09,24,Control,...,122554,0,0.011788,True,15093,0,NaN,0.000000,0.227704,NaN
19,20,ok,,4x,50000,AAV6,EGFP,5.000000e+09,24,Control,...,129442,0,0.011765,True,11249,0,NaN,0.000000,0.229849,NaN
20,21,ok,,4x,50000,AAV6,EGFP,5.000000e+09,24,Control,...,105970,0,0.011767,True,15550,0,NaN,0.000000,0.201390,NaN
21,22,ok,,4x,50000,AAV6,EGFP,2.500000e+09,24,Control,...,120023,0,0.011771,True,14238,0,NaN,0.000000,0.187336,NaN
22,23,ok,,4x,50000,AAV6,EGFP,2.500000e+09,24,Control,...,125492,0,0.011784,True,19620,0,NaN,0.000000,0.149791,NaN
23,24,ok,,4x,50000,AAV6,EGFP,2.500000e+09,24,Control,...,98134,0,0.011768,True,7835,0,NaN,0.000000,0.175979,NaN
24,25,ok,,4x,50000,AAV9,EGFP,5.000000e+10,24,EGFRvIII,...,163556,16364,0.155557,False,7766,2116,0.129308,0.272470,0.159086,0.196584
25,26,ok,,4x,50000,AAV9,EGFP,5.000000e+10,24,EGFRvIII,...,147981,13778,0.163865,False,8148,1631,0.118377,0.200172,0.174302,0.177740
26,27,ok,,4x,50000,AAV9,EGFP,5.000000e+10,24,EGFRvIII,...,132914,15682,0.169881,False,11049,1542,0.098329,0.139560,0.180397,0.192963
27,28,ok,,4x,50000,AAV9,EGFP,2.500000e+10,24,EGFRvIII,...,147387,16116,0.159134,False,7962,1168,0.072475,0.146697,0.118263,0.118836
28,29,ok,,4x,50000,AAV9,EGFP,2.500000e+10,24,EGFRvIII,...,108657,12576,0.139009,False,10395,1949,0.154978,0.187494,0.148535,0.158185
29,30,ok,,4x,50000,AAV9,EGFP,2.500000e+10,24,EGFRvIII,...,130019,12588,0.151948,False,7995,978,0.077693,0.122326,0.149486,0.155475
30,31,ok,,4x,50000,AAV9,EGFP,5.000000e+09,24,EGFRvIII,...,133407,15752,0.171383,False,3576,295,0.018728,0.082494,0.117172,0.116943
31,32,ok,,4x,50000,AAV9,EGFP,5.000000e+09,24,EGFRvIII,...,116223,12721,0.121292,False,1763,526,0.041349,0.298355,0.145756,0.140580
32,33,ok,,4x,50000,AAV9,EGFP,5.000000e+09,24,EGFRvIII,...,109086,13236,0.156113,False,2927,544,0.041100,0.185856,0.138743,0.139828
33,34,ok,,4x,50000,AAV9,EGFP,2.500000e+09,24,EGFRvIII,...,131244,13587,0.138281,False,3707,276,0.020314,0.074454,0.126700,0.128645
34,35,ok,,4x,50000,AAV9,EGFP,2.500000e+09,24,EGFRvIII,...,84970,12242,0.119569,False,1400,522,0.042640,0.372857,0.139359,0.139434
35,36,ok,,4x,50000,AAV9,EGFP,2.500000e+09,24,EGFRvIII,...,98478,11537,0.109240,False,2184,38,0.003294,0.017399,0.125806,0.119608
36,37,ok,,4x,50000,AAV9,EGFP,5.000000e+10,24,Control,...,105908,0,0.011765,True,12678,0,NaN,0.000000,0.177145,NaN
37,38,ok,,4x,50000,AAV9,EGFP,5.000000e+10,24,Control,...,98509,0,0.011765,True,12126,0,NaN,0.000000,0.180760,NaN
38,39,ok,,4x,50000,AAV9,EGFP,5.000000e+10,24,Control,...,114877,0,0.013540,True,12914,0,NaN,0.000000,0.169485,NaN
39,40,ok,,4x,50000,AAV9,EGFP,2.500000e+10,24,Control,...,86217,0,0.011791,True,7354,0,NaN,0.000000,0.136917,NaN
40,41,ok,,4x,50000,AAV9,EGFP,2.500000e+10,24,Control,...,98575,0,0.011765,True,8486,0,NaN,0.000000,0.132615,NaN
41,42,ok,,4x,50000,AAV9,EGFP,2.500000e+10,24,Control,...,93039,0,0.011777,True,4159,0,NaN,0.000000,0.122953,NaN
42,43,ok,,4x,50000,AAV9,EGFP,5.000000e+09,24,Control,...,94812,0,0.011765,True,1762,0,NaN,0.000000,0.135877,NaN
43,44,ok,,4x,50000,AAV9,EGFP,5.000000e+09,24,Control,...,99374,0,0.011767,True,3017,0,NaN,0.000000,0.136702,NaN
44,45,ok,,4x,50000,AAV9,EGFP,5.000000e+09,24,Control,...,91434,0,0.011765,True,925,0,NaN,0.000000,0.138819,NaN
45,46,ok,,4x,50000,AAV9,EGFP,2.500000e+09,24,Control,...,97769,0,0.011765,True,2308,0,NaN,0.000000,0.133741,NaN
46,47,ok,,4x,50000,AAV9,EGFP,2.500000e+09,24,Control,...,103084,0,0.011768,True,2340,0,NaN,0.000000,0.131547,NaN
47,48,ok,,4x,50000,AAV9,EGFP,2.500000e+09,24,Control,...,86540,0,0.011765,True,1267,0,NaN,0.000000,0.128768,NaN

In [21]:
import importlib
import cellseg.plot
importlib.reload(cellseg.plot)

from cellseg.plot import simple_bubble_plot
import bokeh.io
bokeh.io.output_notebook()

df_plot = df_results[df_results["status"] == "ok"].copy()
df_plot["g_area_over_bf"] = df_plot["g_area"] / df_plot["bf_area"]

df_plot = (
    df_plot
    .groupby(["virus", "receptor", "dose_vg/well"])
    .mean(numeric_only=True)
    .reset_index()
)

for receptor in ["EGFRvIII", "Control"]:
    p = simple_bubble_plot(
        df_plot[df_plot["receptor"] == receptor],
        x="virus",
        y="dose_vg/well",
        size="g_area_over_bf",
        color="g_intensity_all",
        x_order=["AAV6", "AAV9"],
        y_order=[5e10, 2.5e10, 5e9, 2.5e9],
        size_range=(5, 38),
        width=400,
        height=360,
        title=receptor,
    )
    p.yaxis.axis_label = "Dose (v.g./well)"
    bokeh.io.show(p)

print(df_plot.head())

p = simple_bubble_plot(
    df_plot[df_plot["receptor"] == "EGFRvIII"],
    x="virus",
    y="dose_vg/well",
    size="overlap_g",
    color="g_intensity_overlap",
    x_order=["AAV6", "AAV9"],
    y_order=[5e10, 2.5e10, 5e9, 2.5e9],
    size_range=(5, 38),
    width=400,
    height=360,
    title="EGFRvIII",
)
p.yaxis.axis_label = "Dose (v.g./well)"
bokeh.io.show(p)

  virus  receptor  dose_vg/well  experiment_id  seeding_density  image_time_h  \
0  AAV6   Control  2.500000e+09           23.0          50000.0          24.0
1  AAV6   Control  5.000000e+09           20.0          50000.0          24.0
2  AAV6   Control  2.500000e+10           17.0          50000.0          24.0
3  AAV6   Control  5.000000e+10           14.0          50000.0          24.0
4  AAV6  EGFRvIII  2.500000e+09           11.0          50000.0          24.0

         bf_area        r_area  r_intensity  r_filter        g_area  \
0  114549.666667      0.000000     0.011774       1.0  13897.666667
1  119322.000000      0.000000     0.011773       1.0  13964.000000
2   99743.666667      0.000000     0.012201       1.0  16955.333333
3  114026.000000      0.000000     0.016265       1.0  27963.000000
4  129745.666667  15506.666667     0.162468       0.0  14712.333333

   overlapping_area  overlap_r  overlap_g  g_intensity_all  \
0          0.000000        NaN   0.000000         0.171035
1          0.000000        NaN   0.000000         0.219648
2          0.000000        NaN   0.000000         0.382640
3          0.000000        NaN   0.000000         0.557083
4       2736.666667   0.179941   0.186331         0.192353

   g_intensity_overlap  g_area_over_bf
0                  NaN        0.118271
1                  NaN        0.118932
2                  NaN        0.175711
3                  NaN        0.244460
4             0.220042        0.114806