# In vitro assay analysis


## Directory structure

Data is organized in the following structure:

```
data/
├── metadata.csv
├── images/
│   ├── 1_bf.tif
│   ├── 1_g.tif
│   ├── 1_r.tif
│   ├── 2_0.tif
│   └── ...

## metadata.csv example
figure_name,figure_id,channel,seeding_density,virus,cargo,dose_vg/well,image_time_h,receptor,include,notes
1_bf.tif,1,brightfield,0.5e5,AAV9,EGFP,0.5e10,24,EGFRvIII,1,
1_r.tif,1,brightfield,0.5e5,AAV9,EGFP,0.5e10,24,EGFRvIII,1,
```

In [2]:
import pandas as pd
from cellseg.metadata import metadata

data = '/Users/longwei/Desktop/janglab/figures/2026-05-23-in_vitro_assay_transduction_48h/'
meta = data + 'metadata.csv'
result = data + 'in_vitro_assay_results.csv'
# Load or generate metadata
df_metadata = metadata(data_dir=data, verbose=True)
print("\nMetadata:")
df_metadata

Looking for metadata file at: /Users/longwei/Desktop/janglab/figures/2026-05-23-in_vitro_assay_transduction_48h/metadata.csv
Looking for images in: /Users/longwei/Desktop/janglab/figures/2026-05-23-in_vitro_assay_transduction_48h/
✓ Found and loaded metadata file (144 rows)

Metadata:

,figure_name,figure_id,experiment_id,magnification,channel,seeding_density,virus,cargo,dose_vg/well,image_time_h,receptor,include,notes
0,Image001.tif,1,1,4x,bf,50000,AAV6,EGFP,5.000000e+10,48,EGFRvIII,1,NaN
1,Image002.tif,2,1,4x,r,50000,AAV6,EGFP,5.000000e+10,48,EGFRvIII,1,NaN
2,Image003.tif,3,1,4x,g,50000,AAV6,EGFP,5.000000e+10,48,EGFRvIII,1,NaN
3,Image004.tif,4,2,4x,bf,50000,AAV6,EGFP,5.000000e+10,48,EGFRvIII,1,NaN
4,Image005.tif,5,2,4x,r,50000,AAV6,EGFP,5.000000e+10,48,EGFRvIII,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,Image140.tif,140,47,4x,r,50000,AAV9,EGFP,2.500000e+09,48,Control,1,NaN
140,Image141.tif,141,47,4x,g,50000,AAV9,EGFP,2.500000e+09,48,Control,1,NaN
141,Image142.tif,142,48,4x,bf,50000,AAV9,EGFP,2.500000e+09,48,Control,1,NaN
142,Image143.tif,143,48,4x,r,50000,AAV9,EGFP,2.500000e+09,48,Control,1,NaN
143,Image144.tif,144,48,4x,g,50000,AAV9,EGFP,2.500000e+09,48,Control,1,NaN

In [6]:
from cellseg.quant import assay_rg_overlap_analysis

df_results = assay_rg_overlap_analysis(
    df_metadata,
    image_directory=data,
    output_file='rg_overlap_results.csv',
    bf_label='bf',
    r_label='r',
    g_label='g',
    r_channel=0,
    g_channel=1,
    min_r_intensity=0.05,
)

Processing RG overlap: 100%|██████████| 48/48 [01:36<00:00,  2.02s/it]

In [7]:
df_results

,experiment_id,status,error,magnification,seeding_density,virus,cargo,dose_vg/well,image_time_h,receptor,...,bf_area,r_area,r_intensity,r_filter,g_area,overlapping_area,overlap_r,overlap_g,g_intensity_all,g_intensity_overlap
0,1,ok,,4x,50000,AAV6,EGFP,5.000000e+10,48,EGFRvIII,...,152820,11557,0.157596,False,54547,5516,0.477286,0.101124,0.719856,0.770331
1,2,ok,,4x,50000,AAV6,EGFP,5.000000e+10,48,EGFRvIII,...,144481,9025,0.196124,False,62083,5390,0.597230,0.086819,0.754932,0.834945
2,3,ok,,4x,50000,AAV6,EGFP,5.000000e+10,48,EGFRvIII,...,146380,8571,0.160161,False,56511,3768,0.439622,0.066677,0.716706,0.757251
3,4,ok,,4x,50000,AAV6,EGFP,2.500000e+10,48,EGFRvIII,...,139295,10635,0.175226,False,45279,5332,0.501363,0.117759,0.589745,0.663545
4,5,ok,,4x,50000,AAV6,EGFP,2.500000e+10,48,EGFRvIII,...,120479,8123,0.156298,False,45333,4580,0.563831,0.101030,0.605003,0.671862
5,6,ok,,4x,50000,AAV6,EGFP,2.500000e+10,48,EGFRvIII,...,94438,5727,0.133704,False,31499,2640,0.460974,0.083812,0.531799,0.544975
6,7,ok,,4x,50000,AAV6,EGFP,5.000000e+09,48,EGFRvIII,...,135149,12279,0.186255,False,38083,4162,0.338953,0.109288,0.394881,0.498398
7,8,ok,,4x,50000,AAV6,EGFP,5.000000e+09,48,EGFRvIII,...,112191,8450,0.169181,False,35192,3367,0.398462,0.095675,0.375889,0.499700
8,9,ok,,4x,50000,AAV6,EGFP,5.000000e+09,48,EGFRvIII,...,129449,11079,0.188582,False,35054,4727,0.426663,0.134849,0.385615,0.459360
9,10,ok,,4x,50000,AAV6,EGFP,2.500000e+09,48,EGFRvIII,...,165814,13539,0.163974,False,29198,3388,0.250240,0.116035,0.330782,0.435758
10,11,ok,,4x,50000,AAV6,EGFP,2.500000e+09,48,EGFRvIII,...,129296,10127,0.171945,False,32219,5306,0.523946,0.164685,0.328781,0.452889
11,12,ok,,4x,50000,AAV6,EGFP,2.500000e+09,48,EGFRvIII,...,124857,10658,0.181294,False,29053,2959,0.277632,0.101848,0.345820,0.460126
12,13,ok,,4x,50000,AAV6,EGFP,5.000000e+10,48,Control,...,106477,0,0.011786,True,47451,0,NaN,0.000000,0.684300,NaN
13,14,ok,,4x,50000,AAV6,EGFP,5.000000e+10,48,Control,...,99153,0,0.011778,True,39834,0,NaN,0.000000,0.711886,NaN
14,15,ok,,4x,50000,AAV6,EGFP,5.000000e+10,48,Control,...,110326,0,0.026159,True,51010,0,NaN,0.000000,0.712561,NaN
15,16,ok,,4x,50000,AAV6,EGFP,2.500000e+10,48,Control,...,90729,0,0.011764,True,28805,0,NaN,0.000000,0.551641,NaN
16,17,ok,,4x,50000,AAV6,EGFP,2.500000e+10,48,Control,...,106718,0,0.011765,True,39784,0,NaN,0.000000,0.539008,NaN
17,18,ok,,4x,50000,AAV6,EGFP,2.500000e+10,48,Control,...,98748,0,0.011765,True,37759,0,NaN,0.000000,0.565802,NaN
18,19,ok,,4x,50000,AAV6,EGFP,5.000000e+09,48,Control,...,112880,0,0.011765,True,33884,0,NaN,0.000000,0.371235,NaN
19,20,ok,,4x,50000,AAV6,EGFP,5.000000e+09,48,Control,...,110208,0,0.011765,True,34432,0,NaN,0.000000,0.361778,NaN
20,21,ok,,4x,50000,AAV6,EGFP,5.000000e+09,48,Control,...,100037,0,0.011773,True,28980,0,NaN,0.000000,0.337901,NaN
21,22,ok,,4x,50000,AAV6,EGFP,2.500000e+09,48,Control,...,115520,0,0.011774,True,26896,0,NaN,0.000000,0.284414,NaN
22,23,ok,,4x,50000,AAV6,EGFP,2.500000e+09,48,Control,...,107421,0,0.011546,True,20487,0,NaN,0.000000,0.271692,NaN
23,24,ok,,4x,50000,AAV6,EGFP,2.500000e+09,48,Control,...,95674,0,0.011765,True,21231,0,NaN,0.000000,0.270482,NaN
24,25,ok,,4x,50000,AAV9,EGFP,5.000000e+10,48,EGFRvIII,...,160975,10952,0.160972,False,18825,4236,0.386779,0.225020,0.253273,0.307644
25,26,ok,,4x,50000,AAV9,EGFP,5.000000e+10,48,EGFRvIII,...,152397,9232,0.161421,False,13927,1846,0.199957,0.132548,0.253078,0.356642
26,27,ok,,4x,50000,AAV9,EGFP,5.000000e+10,48,EGFRvIII,...,130534,9545,0.171545,False,15958,2321,0.243164,0.145444,0.279306,0.331786
27,28,ok,,4x,50000,AAV9,EGFP,2.500000e+10,48,EGFRvIII,...,141676,9121,0.142594,False,10187,592,0.064905,0.058113,0.186228,0.224470
28,29,ok,,4x,50000,AAV9,EGFP,2.500000e+10,48,EGFRvIII,...,128533,8969,0.185708,False,11655,2659,0.296466,0.228142,0.233605,0.328853
29,30,ok,,4x,50000,AAV9,EGFP,2.500000e+10,48,EGFRvIII,...,136607,8304,0.171090,False,10777,928,0.111753,0.086109,0.192429,0.222029
30,31,ok,,4x,50000,AAV9,EGFP,5.000000e+09,48,EGFRvIII,...,161285,12193,0.183713,False,8958,970,0.079554,0.108283,0.125587,0.122163
31,32,ok,,4x,50000,AAV9,EGFP,5.000000e+09,48,EGFRvIII,...,113765,7493,0.158119,False,7065,1441,0.192313,0.203963,0.121037,0.123520
32,33,ok,,4x,50000,AAV9,EGFP,5.000000e+09,48,EGFRvIII,...,123163,10527,0.188463,False,9131,1908,0.181248,0.208958,0.126693,0.133574
33,34,ok,,4x,50000,AAV9,EGFP,2.500000e+09,48,EGFRvIII,...,153473,10418,0.163827,False,6049,456,0.043770,0.075384,0.119659,0.120055
34,35,ok,,4x,50000,AAV9,EGFP,2.500000e+09,48,EGFRvIII,...,105604,5962,0.135075,False,6590,1198,0.200939,0.181791,0.136033,0.140512
35,36,ok,,4x,50000,AAV9,EGFP,2.500000e+09,48,EGFRvIII,...,119790,7735,0.149037,False,5887,787,0.101745,0.133684,0.126860,0.127658
36,37,ok,,4x,50000,AAV9,EGFP,5.000000e+10,48,Control,...,109750,0,0.011765,True,14089,0,NaN,0.000000,0.267072,NaN
37,38,ok,,4x,50000,AAV9,EGFP,5.000000e+10,48,Control,...,103223,0,0.011765,True,11708,0,NaN,0.000000,0.261587,NaN
38,39,ok,,4x,50000,AAV9,EGFP,5.000000e+10,48,Control,...,123840,0,0.012310,True,16286,0,NaN,0.000000,0.291297,NaN
39,40,ok,,4x,50000,AAV9,EGFP,2.500000e+10,48,Control,...,104927,0,0.010856,True,14225,0,NaN,0.000000,0.181196,NaN
40,41,ok,,4x,50000,AAV9,EGFP,2.500000e+10,48,Control,...,107693,0,0.011765,True,12732,0,NaN,0.000000,0.191244,NaN
41,42,ok,,4x,50000,AAV9,EGFP,2.500000e+10,48,Control,...,107043,0,0.011292,True,7458,0,NaN,0.000000,0.201782,NaN
42,43,ok,,4x,50000,AAV9,EGFP,5.000000e+09,48,Control,...,85351,0,0.011769,True,8997,0,NaN,0.000000,0.132370,NaN
43,44,ok,,4x,50000,AAV9,EGFP,5.000000e+09,48,Control,...,100292,0,0.011549,True,10010,0,NaN,0.000000,0.134118,NaN
44,45,ok,,4x,50000,AAV9,EGFP,5.000000e+09,48,Control,...,106671,0,0.011765,True,8732,0,NaN,0.000000,0.126175,NaN
45,46,ok,,4x,50000,AAV9,EGFP,2.500000e+09,48,Control,...,88097,0,0.011817,True,3645,0,NaN,0.000000,0.132300,NaN
46,47,ok,,4x,50000,AAV9,EGFP,2.500000e+09,48,Control,...,105696,0,0.011768,True,5323,0,NaN,0.000000,0.135351,NaN
47,48,ok,,4x,50000,AAV9,EGFP,2.500000e+09,48,Control,...,98154,0,0.011765,True,4256,0,NaN,0.000000,0.128222,NaN

In [8]:
import importlib
import cellseg.plot
importlib.reload(cellseg.plot)

from cellseg.plot import simple_bubble_plot
import bokeh.io
bokeh.io.output_notebook()

df_plot = df_results[df_results["status"] == "ok"].copy()
df_plot["g_area_over_bf"] = df_plot["g_area"] / df_plot["bf_area"]

df_plot = (
    df_plot
    .groupby(["virus", "receptor", "dose_vg/well"])
    .mean(numeric_only=True)
    .reset_index()
)

for receptor in ["EGFRvIII", "Control"]:
    p = simple_bubble_plot(
        df_plot[df_plot["receptor"] == receptor],
        x="virus",
        y="dose_vg/well",
        size="g_area_over_bf",
        color="g_intensity_all",
        x_order=["AAV6", "AAV9"],
        y_order=[5e10, 2.5e10, 5e9, 2.5e9],
        size_range=(5, 38),
        width=400,
        height=360,
        title=receptor,
    )
    p.yaxis.axis_label = "Dose (v.g./well)"
    bokeh.io.show(p)

print(df_plot.head())

p = simple_bubble_plot(
    df_plot[df_plot["receptor"] == "EGFRvIII"],
    x="virus",
    y="dose_vg/well",
    size="overlap_g",
    color="g_intensity_overlap",
    x_order=["AAV6", "AAV9"],
    y_order=[5e10, 2.5e10, 5e9, 2.5e9],
    size_range=(5, 38),
    width=400,
    height=360,
    title="EGFRvIII",
)
p.yaxis.axis_label = "Dose (v.g./well)"
bokeh.io.show(p)

  virus  receptor  dose_vg/well  experiment_id  seeding_density  image_time_h  \
0  AAV6   Control  2.500000e+09           23.0          50000.0          48.0
1  AAV6   Control  5.000000e+09           20.0          50000.0          48.0
2  AAV6   Control  2.500000e+10           17.0          50000.0          48.0
3  AAV6   Control  5.000000e+10           14.0          50000.0          48.0
4  AAV6  EGFRvIII  2.500000e+09           11.0          50000.0          48.0

         bf_area        r_area  r_intensity  r_filter        g_area  \
0  106205.000000      0.000000     0.011695       1.0  22871.333333
1  107708.333333      0.000000     0.011767       1.0  32432.000000
2   98731.666667      0.000000     0.011764       1.0  35449.333333
3  105318.666667      0.000000     0.016575       1.0  46098.333333
4  139989.000000  11441.333333     0.172404       0.0  30156.666667

   overlapping_area  overlap_r  overlap_g  g_intensity_all  \
0          0.000000        NaN   0.000000         0.275529
1          0.000000        NaN   0.000000         0.356971
2          0.000000        NaN   0.000000         0.552150
3          0.000000        NaN   0.000000         0.702916
4       3884.333333   0.350606   0.127523         0.335128

   g_intensity_overlap  g_area_over_bf
0                  NaN        0.215151
1                  NaN        0.300766
2                  NaN        0.357552
3                  NaN        0.436582
4             0.449591        0.219322